### ISSUE TITLE
Malformed links when leaving out protocol

### ISSUE THREAD

**Issue by ibcs01** [maorbarel/v-linkify#1]
Hi,

Thanks for creating this library! I like it a lot that it has no dependencies.

I've found an issue with the link parser that i want to report.

When leaving out the protocol ( e.g. http or https ) the links all malformed.

For example:  "www.domain.com/some-page/test" (without the quotes of course).

The result is the following link:
```
<a target="_blank" href="//<a target=" _blank"="">www.domain.com/some-page/test</a>
">www.domain.com/some-page/test
```

If you have time please look into it.

Thanks!

**Comment by MaorCapital** [comment]
@ibcs01  thanks for report! will fix it soon as possible ( in the next 3 days...)

**Comment by janjoost-denbrinker** [comment]
I have noticed the same problem.

**Comment by janjoost-denbrinker** [comment]
![](https://media.giphy.com/media/l0HTYUmU67pLWv1a8/giphy.gif)
