### ISSUE TITLE
Reactivity

### ISSUE THREAD

**Issue by danbaechtold** [maorbarel/v-linkify#3]
Hi,

Thanks for this helpful directive :)

I have one issue with it, that it does not re-render when the content changes. Probably not only the "bind" hook should be used, but the "update" hook as well (maybe optional?).

Example:
`<div v-linkify>{{ text }}</div>`
When "text" is changed (data), then it does not refresh (change will not be visible).

Thank you,
Dan

**Comment by maorbarel** [comment]
@danbaechtold DONE #7
